name: very_good_slide_puzzle
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  dart_code_metrics: ^4.12.0
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.18
  just_audio_libwinmedia: ^0.0.4
  rive: ^0.8.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/
    - assets/images/dashatar/gallery/
    - assets/images/dashatar/success/
    - assets/images/dashatar/green/
    - assets/images/dashatar/blue/
    - assets/images/dashatar/yellow/
    - assets/images/space/gallery/
    - assets/images/space/success/
    - assets/images/space/constellations_first/
    - assets/images/space/galaxy_first/
    - assets/images/space/galaxy_second/
    - assets/images/space/galaxy_third/
    - assets/images/space/milkyway/
    - assets/images/space/moon/
    - assets/images/space/night/
    - assets/images/space/orion/
    - assets/images/animals/gallery/
    - assets/images/animals/success/
    - assets/images/animals/bird/
    - assets/images/animals/cat/
    - assets/images/animals/guinea/
    - assets/images/animals/horse/
    - assets/images/animals/penguin/
    - assets/images/animals/rabbit/
    - assets/images/animals/tiger/
    - assets/images/animals/turtle/
    - assets/images/castles/gallery/
    - assets/images/castles/success/
    - assets/images/castles/architecture/
    - assets/images/castles/castle_first/
    - assets/images/castles/castle_second/
    - assets/images/castles/fairytale/
    - assets/images/castles/heaven/
    - assets/images/castles/moon/
    - assets/images/castles/neuschwanstein/
    - assets/images/castles/water/
    - assets/images/cities/gallery/
    - assets/images/cities/success/
    - assets/images/cities/buildings_first/
    - assets/images/cities/buildings_second/
    - assets/images/cities/buildings_third/
    - assets/images/cities/city/
    - assets/images/cities/kuala/
    - assets/images/cities/paris/
    - assets/images/cities/pedestrians/
    - assets/images/cities/river/
    - assets/images/dinosaurs/gallery/
    - assets/images/dinosaurs/success/
    - assets/images/dinosaurs/dinosaur_first/
    - assets/images/dinosaurs/dinosaur_second/
    - assets/images/dinosaurs/dinosaur_third/
    - assets/images/dinosaurs/dinosaur_fourth/
    - assets/images/dinosaurs/dinosaur_fifth/
    - assets/images/dinosaurs/dinosaur_sixth/
    - assets/images/dinosaurs/dinosaur_seventh/
    - assets/images/dinosaurs/dinosaur_eighth/
    - assets/images/zen/gallery/
    - assets/images/zen/success/
    - assets/images/zen/abstract/
    - assets/images/zen/beach/
    - assets/images/zen/buddha_first/
    - assets/images/zen/buddha_second/
    - assets/images/zen/buddha_third/
    - assets/images/zen/frogs/
    - assets/images/zen/meditate/
    - assets/images/zen/stones/
    - assets/audio/music/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
